server:
  port: 8081

spring:
  application:
    name: go-around-api
  profiles:
    active: local
    include:
      - mysql-domain
      - go-around-jwt

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false